name: Build

on:
  push:

jobs:
  buildlocal:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o release/dlpu-rpc-windows_amd64.exe ./
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o release/dlpu-rpc-linux_amd64 ./
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o release/dlpu-rpc-linux_arm64 ./

      - name: Upload binary files
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: release/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/dlpu-rpc-windows_amd64.exe
            release/dlpu-rpc-linux_amd64 
            release/dlpu-rpc-linux_arm64 

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: hkccr.ccs.tencentyun.com
        username: ${{ secrets.TX_DOCKER_USER }}
        password: ${{ secrets.TX_DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: hkccr.ccs.tencentyun.com/minijwc/dlpu-rpc:latest