name: cicd

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: hkccr.ccs.tencentyun.com
        username: ${{ secrets.TX_DOCKER_USER }}
        password: ${{ secrets.TX_DOCKER_PASS }}
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: .
              platforms: linux/amd64
              push: true
              tags: hkccr.ccs.tencentyun.com/minijwc/dlpu-rpc:latest